name: crystal
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.31.1
    steps:
    - uses: actions/checkout@v1
    - run: crystal build $(find -name '*.cr')
  test:
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.31.1
    steps:
    - uses: actions/checkout@v1
    - run: crystal spec **/
